language: php

os:
  - linux

php:
  - 7.1

matrix:
  include:
    - php: 7.1
      env: PHPSTAN=1

install:
    - composer self-update
    - composer install

script:
  - if ["$PHPSTAN" = "1"]; then bin/phpstan analyse src --level=6 --ansi --no-progress -c phpstan.neon; fi

